apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexagonal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hexagonal
  template:
    metadata:
      labels:
        app: hexagonal
    spec:
      containers:
      - name: hexagonal
        image: hracuityregistrynamev1.azurecr.io/hexagonal-api-oto:v4
        ports:
        - containerPort: 8080
