apiVersion: v1
kind: Service
metadata:
  name: hexagonal-angular-service
spec:
  type: LoadBalancer
  ports:
  - port: 80 # The port the service will be exposed on
    targetPort: 80 # The target port on the Angular container
  selector:
    app: hexagonal-angular # Selects the Angular deployment based on labels
